export const CHANGE_ORIENTATION = 'eventOnChangeOrientation'
export const ON_LOAD_PROGRESS = 'eventOnLoadProgress'
export const SET_CARDS_INTERACTIVE = 'setCardsInteractive'
export const ON_BONUS_GAME_START = 'onBonusGameStart'
export const ON_EVENT_WIN = 'onEventWin'
export const ON_PLAY_BTN = 'onEventPlayButton'
export const ON_SET_SOUNDS_ON_OFF = 'onSetSoundsOnOff'
export const ON_BONUS_GAME_CLOSE = 'onBonusGameClose'
