export const TEXTURE_NAME = 'textureName'
export const TYPE = 'type'
export const NAME = 'name'
export const X = 'x'
export const Y = 'y'
export const ANCHOR_X = 'anchorX'
export const ANCHOR_Y = 'anchorY'
export const SCALE = 'scale'
export const WIDTH = 'width'
export const HEIGHT = 'height'
export const Z_INDEX = 'zIndex'
export const ALPHA = 'alpha'
export const ANIMATIONS = 'animations'
export const TEXT_REF = 'textRef'
export const TEXT_STYLE = 'textStyle'
export const PREFIX_REF = 'prefixRef'
export const POSTFIX_REF = 'postfixRef'

export const LAND = 'land'
export const PORT = 'port'

export const BACKGROUND_COLOR = 'backgroundColor'
export const CSS_VAR_MAIN_BG_COLOR = '--main-bg-color'
